name: publish
on:
  workflow_run:
    workflows: [release]
    types:
      - completed
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Save build (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: build
          retention-days: 90
          path: dist

  publish:
    name: publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Restore build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: savid/status-collector
          tags: |
            type=raw,value=${{ steps.get-latest-tag.outputs.tag }}
            type=raw,value=latest
            type=sha
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
