name: release
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Save build (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: build
          retention-days: 90
          path: dist

  release_dry_run:
    name: release dry run
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Restore build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Release
        run: npx semantic-release --dry-run --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: 'savid'
          GIT_AUTHOR_EMAIL: '1709934+Savid@users.noreply.github.com'
          GIT_COMMITTER_EMAIL: '1709934+Savid@users.noreply.github.com'
          GIT_AUTHOR_NAME: 'Andrew Davis'
          GIT_COMMITTER_NAME: 'Andrew Davis'

  release:
    name: release
    needs: release_dry_run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Restore build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: 'savid'
          GIT_AUTHOR_EMAIL: '1709934+Savid@users.noreply.github.com'
          GIT_COMMITTER_EMAIL: '1709934+Savid@users.noreply.github.com'
          GIT_AUTHOR_NAME: 'Andrew Davis'
          GIT_COMMITTER_NAME: 'Andrew Davis'
